name: Sky-Block Warriors
main: me.kyle.burnett.SkyBlockWarriors.Main
version: ${project.version}
author: Burnett
description: >
             Sky block warrior plugin.
commands:
    skyblockw:
        description: Main command.
        aliases: [sw]
        usage: /<command> arguments